/**
 * Style Dictionary format: Tailwind v4 `@theme` block.
 *
 * Tailwind v4 only generates utilities for CSS variables in its own reserved
 * namespaces (--color-*, --spacing-*, --radius-*, --font-*, --text-*, --shadow-*).
 * A token named `--ucsd-color-action-primary` generates nothing; the same value
 * republished as `--color-action-primary` generates `bg-action-primary`,
 * `text-action-primary`, `border-action-primary`, and so on.
 *
 * We emit `var(--ucsd-*)` rather than literal values on purpose: the utility then
 * resolves through tokens.css at runtime, so Tailwind classes follow dark mode
 * automatically with no `dark:` variant and no second theme block.
 */

/** Token path prefix -> Tailwind namespace. Order matters: first match wins. */
const NAMESPACE_MAP = [
  { prefix: ['color'],      ns: 'color',   drop: 1 },
  { prefix: ['space'],      ns: 'spacing', drop: 1 },
  { prefix: ['radius'],     ns: 'radius',  drop: 1 },
  { prefix: ['elevation'],  ns: 'shadow',  drop: 1 },
  { prefix: ['font', 'family'], ns: 'font', drop: 2 },
  { prefix: ['font', 'weight'], ns: 'font-weight', drop: 2 },
  { prefix: ['breakpoint'], ns: 'breakpoint', drop: 1 },
  { prefix: ['container'],  ns: 'container',  drop: 1 },
];

const startsWith = (path, prefix) => prefix.every((seg, i) => path[i] === seg);

/** `text.md.size` / `text.md.line-height` need bespoke handling: Tailwind pairs them. */
function tailwindName(token) {
  const path = token.path;

  if (path[0] === 'text' && path.length === 3) {
    if (path[2] === 'size') return `--text-${path[1]}`;
    if (path[2] === 'line-height') return `--text-${path[1]}--line-height`;
    return null;
  }

  for (const { prefix, ns, drop } of NAMESPACE_MAP) {
    if (startsWith(path, prefix)) {
      const rest = path.slice(drop).join('-');
      return rest ? `--${ns}-${rest}` : null;
    }
  }
  return null; // primitives and component tokens are intentionally not exposed as utilities
}

export const tailwindTheme = {
  name: 'css/ucsd-tailwind-theme',
  format: ({ dictionary, options }) => {
    const prefix = options?.prefix ?? 'ucsd';
    const lines = [];
    const seen = new Set();

    for (const token of dictionary.allTokens) {
      const name = tailwindName(token);
      if (!name || seen.has(name)) continue;
      seen.add(name);
      lines.push(`  ${name}: var(--${prefix}-${token.name.replace(new RegExp(`^${prefix}-`), '')});`);
    }

    return [
      '/**',
      ' * UCSD Design System — Tailwind v4 theme.',
      ' * GENERATED by @ucsd/tokens. Do not edit.',
      ' *',
      ' * Usage:',
      ' *   @import "tailwindcss";',
      ' *   @import "@ucsd/tokens/css";       // defines --ucsd-* (light + dark)',
      ' *   @import "@ucsd/tokens/tailwind";  // maps them into Tailwind utilities',
      ' */',
      '',
      '@theme {',
      ...lines.sort(),
      '}',
      '',
    ].join('\n');
  },
};
