/**
 * @ucsd/tokens build
 *
 * One DTCG source in `tokens/` -> five outputs, so cross-framework consistency is a
 * property of the build rather than of anyone's discipline.
 *
 *   dist/css/tokens.css       :root + dark-mode block. The universal fallback.
 *   dist/scss/_tokens.scss    compile-time Sass values for Bootstrap 5.
 *   dist/tailwind/theme.css   Tailwind v4 @theme mapping.
 *   dist/js/tokens.js|.d.ts   typed object for React / charts / canvas.
 *   dist/tokens.json          flat manifest -> feeds the docs + the Claude skill.
 *
 * Modes are handled by running Style Dictionary twice over different colour sources.
 * The light pass emits every token; the dark pass emits ONLY the re-aliased colours,
 * scoped to the dark selector. Because CSS output keeps references as `var()`,
 * component tokens such as --ucsd-button-primary-bg follow dark mode for free.
 */

import StyleDictionary from 'style-dictionary';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { tailwindTheme } from './formats/tailwind-theme.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(HERE, '..', '..');
const DIST = path.join(HERE, 'dist');

/** Style Dictionary paths need POSIX separators, including on Windows. */
const posix = (p) => p.split(path.sep).join('/');
const g = (...segs) => posix(path.join(REPO, ...segs));
const DIST_POSIX = posix(DIST);

const PREFIX = 'ucsd';

/** Selectors that opt a subtree into dark mode. Bootstrap 5.3 native + shadcn + generic. */
const DARK_SELECTOR = '[data-bs-theme="dark"], .dark, [data-theme="dark"]';

const COMMON_SOURCES = [
  g('tokens', 'primitive', '**', '*.json'),
  g('tokens', 'semantic', '*.json'),
  g('tokens', 'component', '**', '*.json'),
];

const sourcesFor = (mode) => [...COMMON_SOURCES, g('tokens', 'semantic', 'color', `${mode}.json`)];

/** Values are authored with units already (`16px`), so no size transforms are wanted. */
const TRANSFORMS = ['attribute/cti', 'name/kebab', 'color/css'];

const isDarkToken = (token) => posix(token.filePath).includes('/semantic/color/dark.json');

/**
 * Every platform shares the same transforms and prefix; only the output directory
 * and file list differ. Declaring that once keeps the light and dark passes from
 * drifting apart when a transform is added.
 */
const platform = (dir, files) => ({
  transforms: TRANSFORMS,
  prefix: PREFIX,
  buildPath: `${DIST_POSIX}/${dir}`,
  files,
});

// ---------------------------------------------------------------------------
// Custom formats
// ---------------------------------------------------------------------------

/**
 * A DTCG alias, or null if the value is a literal. Same predicate as `isRef` in
 * scripts/validate-tokens.mjs — keep the two in step.
 */
const asReference = (v) => (typeof v === 'string' && /^\{[^}]+\}$/.test(v) ? v : null);

/** Flat manifest consumed by the docs site and `scripts/generate-skill-references.mjs`. */
const manifest = {
  name: 'json/ucsd-manifest',
  format: ({ dictionary }) =>
    JSON.stringify(
      dictionary.allTokens.map((t) => ({
        name: t.name,
        cssVar: `--${t.name}`,
        path: t.path.join('.'),
        tier: t.filePath.includes('primitive') ? 'primitive'
            : t.filePath.includes('component') ? 'component'
            : 'semantic',
        type: t.$type ?? t.type ?? null,
        value: t.$value ?? t.value,
        reference: asReference(t.original?.$value ?? t.original?.value),
        description: t.$description ?? t.comment ?? null,
      })),
      null,
      2,
    ) + '\n',
};

/** ESM object + declaration file. Hand-rolled to keep identifiers predictable. */
const jsModule = {
  name: 'javascript/ucsd-esm',
  format: ({ dictionary }) => {
    const entries = dictionary.allTokens
      .map((t) => `  '${t.path.join('.')}': ${JSON.stringify(t.$value ?? t.value)},`)
      .join('\n');
    return `// GENERATED by @ucsd/tokens. Do not edit.\nexport const tokens = {\n${entries}\n};\n\nexport default tokens;\n`;
  },
};

const jsTypes = {
  name: 'typescript/ucsd-dts',
  format: ({ dictionary }) => {
    const keys = dictionary.allTokens.map((t) => `  '${t.path.join('.')}': string;`).join('\n');
    return `// GENERATED by @ucsd/tokens. Do not edit.\nexport declare const tokens: {\n${keys}\n};\nexport default tokens;\n`;
  },
};

for (const f of [tailwindTheme, manifest, jsModule, jsTypes]) {
  StyleDictionary.registerFormat(f);
}

// ---------------------------------------------------------------------------
// Passes
// ---------------------------------------------------------------------------

const lightPass = new StyleDictionary({
  source: sourcesFor('light'),
  log: { verbosity: 'default', warnings: 'warn' },
  platforms: {
    css: platform('css/', [{
      destination: '_root.css',
      format: 'css/variables',
      options: { selector: ':root', outputReferences: true },
    }]),
    scss: platform('scss/', [{
      destination: '_tokens.scss',
      format: 'scss/variables',
      // Bootstrap needs literal values at compile time to build its own maps,
      // so references are resolved here rather than emitted as var().
      options: { outputReferences: false },
    }]),
    tailwind: platform('tailwind/', [
      { destination: 'theme.css', format: 'css/ucsd-tailwind-theme' },
    ]),
    js: platform('js/', [
      { destination: 'tokens.js',   format: 'javascript/ucsd-esm' },
      { destination: 'tokens.d.ts', format: 'typescript/ucsd-dts' },
    ]),
    manifest: platform('', [
      { destination: 'tokens.json', format: 'json/ucsd-manifest' },
    ]),
  },
});

const darkPass = new StyleDictionary({
  source: sourcesFor('dark'),
  // Warnings are disabled here for one specific, expected case: the dark block
  // references primitives that are filtered OUT of its own output because they
  // already live in :root from the light pass. Style Dictionary flags that as
  // "filtered out token references"; here it is the intended design, and the
  // resulting `var(--ucsd-palette-*)` resolves correctly at runtime.
  log: { verbosity: 'default', warnings: 'disabled' },
  platforms: {
    css: platform('css/', [{
      destination: '_dark.css',
      format: 'css/variables',
      filter: isDarkToken,
      options: { selector: DARK_SELECTOR, outputReferences: true },
    }]),
    manifest: platform('', [
      { destination: 'tokens.dark.json', format: 'json/ucsd-manifest', filter: isDarkToken },
    ]),
  },
});

// ---------------------------------------------------------------------------
// Run
// ---------------------------------------------------------------------------

// maxRetries: Windows throws EBUSY when an editor, indexer or AV scanner holds a
// handle on dist/. Retrying briefly is the standard mitigation.
await fs.rm(DIST, { recursive: true, force: true, maxRetries: 10, retryDelay: 100 });

// The passes read disjoint sources and write disjoint files, so there is no
// ordering dependency between them.
await Promise.all([lightPass.buildAllPlatforms(), darkPass.buildAllPlatforms()]);

// Stitch the two CSS blocks into the single file consumers import.
const cssDir = path.join(DIST, 'css');
const [root, dark] = await Promise.all([
  fs.readFile(path.join(cssDir, '_root.css'), 'utf8'),
  fs.readFile(path.join(cssDir, '_dark.css'), 'utf8'),
]);

const banner = `/**
 * UCSD Design System tokens.
 * GENERATED by @ucsd/tokens — do not edit. Change values in Figma; see docs/figma-pipeline.md.
 *
 * Dark mode activates under: ${DARK_SELECTOR}
 */
`;

const stripBanner = (s) => s.replace(/^\/\*\*[\s\S]*?\*\/\s*/, '');

await fs.writeFile(
  path.join(cssDir, 'tokens.css'),
  `${banner}\n${stripBanner(root)}\n${stripBanner(dark)}`,
  'utf8',
);
await Promise.all([
  fs.rm(path.join(cssDir, '_root.css')),
  fs.rm(path.join(cssDir, '_dark.css')),
]);

const count = JSON.parse(await fs.readFile(path.join(DIST, 'tokens.json'), 'utf8')).length;
console.log(`\n@ucsd/tokens: built ${count} tokens -> ${path.relative(REPO, DIST)}`);
